"""Image prompt agent with LLM-first prompt planning."""

from __future__ import annotations

import json
import re
from typing import Any
from urllib import error as urlerror
from urllib import request as urlrequest

from backend.models.schemas import EntityExtraction, ImagePromptItem, ImagePrompts, NodeText


class ImagePromptAgent:
    """Build image prompts from node content, preferring text-model planning."""

    _MINIMAX_TEXT_ENDPOINT = "https://api.minimaxi.com/v1/text/chatcompletion_v2"
    _WHATAI_TEXT_ENDPOINT = "https://api.whatai.cc/v1/chat/completions"
    _JSON_BLOCK_PATTERN = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", flags=re.S)
    _VISIBLE_TEXT_CHINESE_RULE = (
        "如果画面中出现任何标签、标识牌、屏幕文字、设备铭牌、箭头说明、流程节点或注释文字，"
        "这些可见文字必须全部使用中文。"
    )
    _ALLOWED_STYLE_PRESETS = {
        "engineering_site_photo": {
            "label": "工程实景图",
            "default_aspect_ratio": "3:2",
            "style_rule": (
                "必须呈现为真实工程现场纪实摄影，画面主体应是设备、机房、站房、柜体、桥架、管线或安装现场，"
                "可以出现工程标识框、箭头、小型标签或铭牌细节，但只要画面中出现文字，必须全部使用中文，"
                "绝对不能出现任何人物、施工人员或摆拍对象。"
            ),
        },
        "engineering_structure_flow_diagram": {
            "label": "工程结构流程图",
            "default_aspect_ratio": "2:1",
            "style_rule": (
                "必须呈现为专业工程结构流程图、控制逻辑图、网络拓扑图或模块关系图，"
                "强调模块层级、流程箭头、连接关系和结构组织，图中的所有标签、模块名、箭头说明和注释文字必须使用中文。"
            ),
        },
    }
    _ALLOWED_ASPECT_RATIOS = {"2:1", "3:2"}
    _FORBIDDEN_ELEMENTS = [
        "海报式构图",
        "宣传海报风格",
        "封面式大标题",
        "大面积中文标题字",
        "大面积英文标题字",
        "抽象科技光效",
        "卡通插画",
        "与工程无关的人物摆拍",
        "任何人物或施工人员",
        "营销文案",
        "logo、水印、页眉页脚装饰",
    ]

    def build(
        self,
        *,
        entities: EntityExtraction,
        node_text: NodeText,
        prompt_config: dict[str, Any] | None = None,
    ) -> ImagePrompts:
        prompt_count = self._target_prompt_count(entities, node_text)
        if not self._can_use_llm(prompt_config):
            raise RuntimeError(
                "Image prompt generation requires a configured text model. "
                "Prompts must be generated by the LLM from node content context."
            )

        return self._build_with_model(
            entities=entities,
            node_text=node_text,
            prompt_count=prompt_count,
            prompt_config=prompt_config or {},
        )

    def strengthen_prompt(
        self,
        prompt_item: ImagePromptItem,
        *,
        missing_elements: list[str],
        retry_no: int,
    ) -> ImagePromptItem:
        if not missing_elements:
            return prompt_item
        must_have = list(prompt_item.must_have_elements)
        for item in missing_elements:
            cleaned = self._clean_text(item)
            if cleaned and cleaned not in must_have:
                must_have.append(cleaned)
        updated_prompt = (
            f"{prompt_item.prompt.rstrip('。')}。"
            f"第{retry_no}次重试必须补足：{'、'.join(missing_elements)}。"
            "保持当前选定的图片类型和工程风格，不要退化成宣传海报或通用概念图。"
        )
        return prompt_item.model_copy(
            update={
                "prompt": updated_prompt,
                "must_have_elements": must_have,
            }
        )

    def _build_with_model(
        self,
        *,
        entities: EntityExtraction,
        node_text: NodeText,
        prompt_count: int,
        prompt_config: dict[str, Any],
    ) -> ImagePrompts:
        targets = self._collect_targets(node_text)
        prompt = self._build_model_prompt(
            entities=entities,
            node_text=node_text,
            prompt_count=prompt_count,
        )
        provider = str(prompt_config.get("text_provider") or "").strip().lower()
        request_fn = (
            self._request_minimax_completion
            if provider == "minimax"
            else self._request_whatai_completion
        )
        content = request_fn(
            api_key=str(prompt_config.get("text_api_key") or "").strip(),
            model_name=str(prompt_config.get("text_model_name") or "MiniMax-M2.5").strip() or "MiniMax-M2.5",
            prompt=prompt,
        )
        payload = self._extract_json_payload(content)
        raw_items = payload.get("prompts") or []
        if not isinstance(raw_items, list):
            return ImagePrompts(node_uid=node_text.node_uid, prompts=[])

        prompts: list[ImagePromptItem] = []
        used_sections: set[str] = set()
        for index, item in enumerate(raw_items[:prompt_count], start=1):
            if not isinstance(item, dict):
                continue
            bind_section, bind_anchor = self._resolve_target(
                requested_section=str(item.get("bind_section") or "").strip(),
                targets=targets,
                used_sections=used_sections,
            )
            style_preset = self._normalize_style_preset(str(item.get("style_preset") or ""))
            image_type = self._normalize_image_type(str(item.get("image_type") or ""))
            must_have = self._normalize_elements(item.get("must_have_elements"), bind_section, node_text.title)
            prompt_text = self._clean_prompt_text(
                str(item.get("prompt") or ""),
                style_preset=style_preset,
                node_title=node_text.title,
                bind_section=bind_section,
                must_have=must_have,
            )
            prompts.append(
                ImagePromptItem(
                    prompt_id=f"prompt_{index:03d}",
                    image_type=image_type,
                    prompt=prompt_text,
                    style_preset=style_preset,
                    style_variant=None,
                    aspect_ratio=self._normalize_aspect_ratio(
                        str(item.get("aspect_ratio") or ""),
                        style_preset=style_preset,
                    ),
                    must_have_elements=must_have,
                    forbidden_elements=list(self._FORBIDDEN_ELEMENTS),
                    bind_anchor=bind_anchor,
                    bind_section=bind_section,
                )
            )

        required_count = min(prompt_count, len(targets))
        if len(prompts) < required_count:
            raise RuntimeError(
                "Image prompt model did not return enough valid prompts. "
                f"Expected at least {required_count}, got {len(prompts)}."
            )

        return ImagePrompts(node_uid=node_text.node_uid, prompts=prompts[:prompt_count])

    def _build_with_rules(
        self,
        *,
        entities: EntityExtraction,
        node_text: NodeText,
        targets: list[tuple[str, str]],
        prompt_count: int,
    ) -> ImagePrompts:
        del entities, node_text, targets, prompt_count
        raise RuntimeError(
            "Template-based image prompt generation is disabled. "
            "Prompts must be generated by the LLM from node content context."
        )

    def _build_model_prompt(
        self,
        *,
        entities: EntityExtraction,
        node_text: NodeText,
        prompt_count: int,
    ) -> str:
        style_lines = [
            f"- {key}: {item['label']}。{item['style_rule']}"
            for key, item in self._ALLOWED_STYLE_PRESETS.items()
        ]
        section_lines = [
            f"- {section.title}: {' '.join(paragraph.text for paragraph in section.paragraphs[:2])}"
            for section in node_text.sections
        ]
        entity_lines = [
            f"- {item.name} ({item.category})"
            for item in entities.entities[:12]
        ]
        return "\n".join(
            [
                "任务：根据以下节点正文，为工程技术文档生成图片 prompt 规划。",
                f"请输出 {prompt_count} 条图片 prompt，必须基于文档内容自行判断使用哪种图片风格。",
                "只允许选择以下 2 种风格：",
                *style_lines,
                "图片比例只能选择 2:1 或 3:2。",
                "要求：",
                "1. prompt 必须详细、准确、专业，不能写成泛泛的占位语句。",
                "2. prompt 必须明确画面主体、构图、工程对象、标识方式、光线、材质、禁止项。",
                "3. 必须根据正文内容自行判断使用工程实景图或工程结构流程图，禁止使用任何模板 prompt、固定骨架或通用占位语句。",
                f"4. {self._VISIBLE_TEXT_CHINESE_RULE}",
                "5. 如果选择工程实景图，画面中不得出现任何人物、施工人员、巡检人员或摆拍对象。",
                "6. 多张图之间应避免完全重复的画面焦点和场景。",
                "7. bind_section 必须从给定小节标题中选择。",
                "8. 只输出 JSON，不要解释。",
                "",
                "输出 JSON 格式：",
                '{',
                '  "prompts": [',
                '    {',
                '      "bind_section": "小节标题",',
                '      "image_type": "topology|process|layout|acceptance",',
                '      "style_preset": "engineering_site_photo|engineering_structure_flow_diagram",',
                '      "aspect_ratio": "2:1|3:2",',
                '      "must_have_elements": ["元素1", "元素2"],',
                '      "prompt": "详细 prompt"',
                "    }",
                "  ]",
                '}',
                "",
                f"节点标题：{node_text.title}",
                f"节点摘要：{node_text.summary}",
                "小节与正文要点：",
                *(section_lines or ["- 无"]),
                "实体：",
                *(entity_lines or ["- 无"]),
            ]
        )

    def _request_minimax_completion(self, *, api_key: str, model_name: str, prompt: str) -> str:
        payload = {
            "model": model_name,
            "messages": [
                {
                    "role": "system",
                    "name": "Image Prompt Planner",
                    "content": (
                        "你是工程文档配图规划器。"
                        "必须严格依据输入正文和实体，生成详细专业的图片 prompt。"
                        "禁止使用模板化 prompt 或固定场景骨架。"
                    ),
                },
                {"role": "user", "name": "user", "content": prompt},
            ],
            "temperature": 0.3,
        }
        req = urlrequest.Request(
            self._MINIMAX_TEXT_ENDPOINT,
            data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )

        try:
            with urlrequest.urlopen(req, timeout=180) as response:
                body = response.read().decode("utf-8")
        except urlerror.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"Image prompt model request failed: HTTP {exc.code} {detail}") from exc
        except (urlerror.URLError, TimeoutError) as exc:
            raise RuntimeError(f"Image prompt model request failed: {exc}") from exc

        data = json.loads(body)
        base_resp = data.get("base_resp") or {}
        if base_resp.get("status_code") not in (None, 0):
            raise RuntimeError(
                f"Image prompt model returned error: {base_resp.get('status_msg') or base_resp.get('status_code')}"
            )

        content = (
            ((data.get("choices") or [{}])[0].get("message") or {}).get("content")
            if isinstance(data.get("choices"), list)
            else None
        )
        if not isinstance(content, str) or not content.strip():
            raise RuntimeError("Image prompt model returned empty content.")
        return content

    def _request_whatai_completion(self, *, api_key: str, model_name: str, prompt: str) -> str:
        payload = {
            "model": model_name,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "你是工程文档配图规划器。"
                        "必须严格依据输入正文和实体，生成详细专业的图片 prompt。"
                        "禁止使用模板化 prompt 或固定场景骨架。"
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.3,
        }
        req = urlrequest.Request(
            self._WHATAI_TEXT_ENDPOINT,
            data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )

        try:
            with urlrequest.urlopen(req, timeout=180) as response:
                body = response.read().decode("utf-8")
        except urlerror.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"Image prompt model request failed: HTTP {exc.code} {detail}") from exc
        except (urlerror.URLError, TimeoutError) as exc:
            raise RuntimeError(f"Image prompt model request failed: {exc}") from exc

        data = json.loads(body)
        if data.get("error"):
            raise RuntimeError(f"Image prompt model returned error: {data['error']}")

        content = (
            ((data.get("choices") or [{}])[0].get("message") or {}).get("content")
            if isinstance(data.get("choices"), list)
            else None
        )
        if not isinstance(content, str) or not content.strip():
            raise RuntimeError("Image prompt model returned empty content.")
        return content

    def _extract_json_payload(self, content: str) -> dict[str, Any]:
        candidates = self._JSON_BLOCK_PATTERN.findall(content)
        first = content.find("{")
        last = content.rfind("}")
        if first != -1 and last != -1 and first < last:
            candidates.append(content[first : last + 1])

        for candidate in candidates:
            try:
                payload = json.loads(candidate)
            except json.JSONDecodeError:
                continue
            if isinstance(payload, dict):
                return payload
        raise RuntimeError("Image prompt model did not return parsable JSON.")

    def _collect_targets(self, node_text: NodeText) -> list[tuple[str, str]]:
        targets: list[tuple[str, str]] = []
        for section in node_text.sections:
            anchor = None
            for paragraph in section.paragraphs:
                if paragraph.anchors:
                    anchor = paragraph.anchors[0]
                    break
            targets.append((anchor or "anchor_default", section.title))
        if not targets:
            targets.append(("anchor_default", node_text.title))
        return targets

    def _resolve_target(
        self,
        *,
        requested_section: str,
        targets: list[tuple[str, str]],
        used_sections: set[str],
    ) -> tuple[str, str]:
        cleaned = self._clean_text(requested_section)
        if cleaned:
            for anchor, section in targets:
                if section == cleaned and section not in used_sections:
                    used_sections.add(section)
                    return section, anchor
            for anchor, section in targets:
                if cleaned in section and section not in used_sections:
                    used_sections.add(section)
                    return section, anchor
        for anchor, section in targets:
            if section not in used_sections:
                used_sections.add(section)
                return section, anchor
        anchor, section = targets[0]
        return section, anchor

    def _target_prompt_count(self, entities: EntityExtraction, node_text: NodeText) -> int:
        del entities, node_text
        return 2

    @staticmethod
    def _select_prompt_types(entities: EntityExtraction, node_text: NodeText) -> list[str]:
        categories = {item.category for item in entities.entities}
        context = " ".join(
            [
                node_text.title,
                node_text.summary,
                *[section.title for section in node_text.sections],
                *[entity.name for entity in entities.entities],
            ]
        )
        types: list[str] = []
        if "topology" in categories or any(token in context for token in ("网络", "通信", "总线", "拓扑", "架构", "节点")):
            types.append("topology")
        if "layout" in categories or "device" in categories or any(
            token in context for token in ("机柜", "控制柜", "配电柜", "桥架", "接线", "布置", "安装", "柜体", "管线")
        ):
            types.append("layout")
        if "acceptance" in categories or any(token in context for token in ("验收", "调试", "巡检", "测试", "确认")):
            types.append("acceptance")
        if "process" in categories or any(token in context for token in ("流程", "步骤", "联动", "监控", "报警", "整改")):
            types.append("process")

        unique: list[str] = []
        for item in types:
            if item not in unique:
                unique.append(item)
        if len(unique) < 2:
            unique.append("layout")
        if len(unique) < 3:
            unique.append("process")
        return unique[:3]

    @staticmethod
    def _select_elements(
        *,
        image_type: str,
        entities: EntityExtraction,
        node_text: NodeText,
        bind_section: str,
    ) -> list[str]:
        priority = {
            "topology": {"topology", "device", "scene"},
            "process": {"process", "topology", "device"},
            "layout": {"device", "scene", "topology"},
            "acceptance": {"acceptance", "process", "scene"},
        }.get(image_type, {"process", "scene"})

        chosen: list[str] = []
        for entity in entities.entities:
            if entity.category in priority and entity.name not in chosen:
                chosen.append(entity.name)
        for fallback in (bind_section, node_text.title):
            cleaned = fallback.strip()
            if cleaned and cleaned not in chosen:
                chosen.append(cleaned)
        return chosen[:4]

    @staticmethod
    def _context_text(
        *,
        entities: EntityExtraction,
        node_text: NodeText,
        bind_section: str,
    ) -> str:
        return " ".join(
            [
                node_text.title,
                node_text.summary,
                bind_section,
                *[section.title for section in node_text.sections],
                *[entity.name for entity in entities.entities],
            ]
        )

    def _fallback_style_preset(
        self,
        *,
        image_type: str,
        context: str,
        used_styles: set[str],
    ) -> str:
        del image_type, used_styles
        if any(token in context for token in ("现场", "机房", "站房", "控制室", "配电室", "巡检", "调试")):
            return "engineering_site_photo"
        return "engineering_structure_flow_diagram"

    def _fallback_aspect_ratio(self, style_preset: str, *, image_type: str, context: str) -> str:
        if style_preset == "engineering_structure_flow_diagram":
            return "2:1"
        if any(token in context for token in ("总览", "拓扑", "流程", "链路")):
            return "2:1"
        return self._ALLOWED_STYLE_PRESETS[style_preset]["default_aspect_ratio"]

    def _render_fallback_prompt(
        self,
        *,
        node_title: str,
        bind_section: str,
        must_have: list[str],
        style_preset: str,
        aspect_ratio: str,
    ) -> str:
        style = self._ALLOWED_STYLE_PRESETS[style_preset]
        return self._clean_prompt_text(
            (
                f"请根据工程技术文档内容生成一张与“{node_title}”相关的配图，重点对应小节“{bind_section}”。"
                f"图片风格必须采用{style['label']}，{style['style_rule']}"
                f"最终画幅必须为{aspect_ratio}横向长图。"
                f"画面必须真实呈现以下工程对象或要素：{'、'.join(must_have)}。"
                "需要明确主体设备、结构关系、关键标识、工程环境和约束条件，"
                "保证图片可以直接用于工程文档正文，不得做成宣传海报、封面图或概念艺术图。"
                f"严格禁止：{', '.join(self._FORBIDDEN_ELEMENTS)}。"
            ),
            style_preset=style_preset,
            node_title=node_title,
            bind_section=bind_section,
            must_have=must_have,
        )

    def _clean_prompt_text(
        self,
        prompt: str,
        *,
        style_preset: str,
        node_title: str,
        bind_section: str,
        must_have: list[str],
    ) -> str:
        cleaned = self._clean_text(prompt)
        if not cleaned:
            raise RuntimeError("Image prompt model returned an empty prompt.")
        if all(item not in cleaned for item in must_have):
            cleaned = f"{cleaned}必须出现{'、'.join(must_have)}。"
        if "中文" not in cleaned:
            cleaned = f"{cleaned}{self._VISIBLE_TEXT_CHINESE_RULE}"
        if style_preset == "engineering_site_photo" and not any(
            token in cleaned for token in ("不得出现任何人员", "不得出现人员", "禁止出现人员", "无人", "空场")
        ):
            cleaned = f"{cleaned}画面中不得出现任何人物或施工人员。"
        if "海报" not in cleaned:
            cleaned = f"{cleaned}禁止海报式排版、整屏大标题和营销风格。"
        return cleaned

    def _normalize_style_preset(self, value: str) -> str:
        normalized = self._clean_text(value)
        if normalized in self._ALLOWED_STYLE_PRESETS:
            return normalized
        if any(token in normalized for token in ("实景", "现场", "摄影", "拍摄")):
            return "engineering_site_photo"
        return "engineering_structure_flow_diagram"

    def _normalize_aspect_ratio(self, value: str, *, style_preset: str) -> str:
        normalized = self._clean_text(value)
        if normalized in self._ALLOWED_ASPECT_RATIOS:
            return normalized
        return self._ALLOWED_STYLE_PRESETS[style_preset]["default_aspect_ratio"]

    def _normalize_image_type(self, value: str) -> str:
        normalized = self._clean_text(value)
        if normalized in {"topology", "process", "layout", "acceptance"}:
            return normalized
        return "process"

    def _normalize_elements(self, raw: Any, bind_section: str, node_title: str) -> list[str]:
        if not isinstance(raw, list):
            raw = []
        items = [self._clean_text(str(item)) for item in raw]
        items = [item for item in items if item]
        for fallback in (bind_section, node_title):
            cleaned = self._clean_text(fallback)
            if cleaned and cleaned not in items:
                items.append(cleaned)
        return items[:4]

    def _can_use_llm(self, prompt_config: dict[str, Any] | None) -> bool:
        if not prompt_config:
            return False
        provider = str(prompt_config.get("text_provider") or "").strip().lower()
        api_key = str(prompt_config.get("text_api_key") or "").strip()
        return provider in {"minimax", "whatai", "google"} and bool(api_key)

    @staticmethod
    def _clean_text(text: str) -> str:
        cleaned = str(text or "").replace("\n", "").replace("\r", "")
        cleaned = re.sub(r"\s+", "", cleaned)
        return cleaned.strip("，。；： ")
